/* tslint:disable */
/* eslint-disable */
/**
 * AllTheBeans-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoffeeUpdateDTO
 */
export interface CoffeeUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof CoffeeUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CoffeeUpdateDTO
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CoffeeUpdateDTO
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CoffeeUpdateDTO
     */
    image?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CoffeeUpdateDTO
     */
    cost?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CoffeeUpdateDTO
     */
    colour?: string | null;
}

/**
 * Check if a given object implements the CoffeeUpdateDTO interface.
 */
export function instanceOfCoffeeUpdateDTO(value: object): value is CoffeeUpdateDTO {
    return true;
}

export function CoffeeUpdateDTOFromJSON(json: any): CoffeeUpdateDTO {
    return CoffeeUpdateDTOFromJSONTyped(json, false);
}

export function CoffeeUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoffeeUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'country': json['country'] == null ? undefined : json['country'],
        'image': json['image'] == null ? undefined : json['image'],
        'cost': json['cost'] == null ? undefined : json['cost'],
        'colour': json['colour'] == null ? undefined : json['colour'],
    };
}

export function CoffeeUpdateDTOToJSON(json: any): CoffeeUpdateDTO {
    return CoffeeUpdateDTOToJSONTyped(json, false);
}

export function CoffeeUpdateDTOToJSONTyped(value?: CoffeeUpdateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'country': value['country'],
        'image': value['image'],
        'cost': value['cost'],
        'colour': value['colour'],
    };
}

