/* tslint:disable */
/* eslint-disable */
/**
 * AllTheBeans-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoffeeCreateDTO
 */
export interface CoffeeCreateDTO {
    /**
     * 
     * @type {string}
     * @memberof CoffeeCreateDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CoffeeCreateDTO
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CoffeeCreateDTO
     */
    country: string;
    /**
     * 
     * @type {string}
     * @memberof CoffeeCreateDTO
     */
    image: string;
    /**
     * 
     * @type {number}
     * @memberof CoffeeCreateDTO
     */
    cost: number;
    /**
     * 
     * @type {string}
     * @memberof CoffeeCreateDTO
     */
    colour: string;
}

/**
 * Check if a given object implements the CoffeeCreateDTO interface.
 */
export function instanceOfCoffeeCreateDTO(value: object): value is CoffeeCreateDTO {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('cost' in value) || value['cost'] === undefined) return false;
    if (!('colour' in value) || value['colour'] === undefined) return false;
    return true;
}

export function CoffeeCreateDTOFromJSON(json: any): CoffeeCreateDTO {
    return CoffeeCreateDTOFromJSONTyped(json, false);
}

export function CoffeeCreateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoffeeCreateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'country': json['country'],
        'image': json['image'],
        'cost': json['cost'],
        'colour': json['colour'],
    };
}

export function CoffeeCreateDTOToJSON(json: any): CoffeeCreateDTO {
    return CoffeeCreateDTOToJSONTyped(json, false);
}

export function CoffeeCreateDTOToJSONTyped(value?: CoffeeCreateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'country': value['country'],
        'image': value['image'],
        'cost': value['cost'],
        'colour': value['colour'],
    };
}

